### ISSUE TITLE
Repo license

### ISSUE THREAD

**Issue by sidkshatriya** [DieracDelta/NixKernelTutorial#1]
Thank you for a very interesting blog accompanied by this tutorial. It truly shows off the power of nix!

If possible, can you add a source license to your repository? (e.g. MIT/GPL/whatever license you think appropriate)

**Comment by sidkshatriya** [comment]
Also it might be a good idea to link back to your blog to provide more context in the README. The blog was very enjoyable!

**Comment by DieracDelta** [comment]
Done. Thanks for the feedback, and really glad you enjoyed the post! (thanks for taking the time to read!)
